name: new_project
description: "An AI model inspired by chatGPT."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  smooth_page_indicator: ^1.0.0
  get: ^4.6.6
  dart_openai: ^5.1.0
  cached_network_image: ^3.4.1
  http: ^1.2.2
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.0

  
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # Corrected indentation

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/loop.png"  # Use forward slashes for paths

flutter:
  uses-material-design: true
  assets:
    - assets/Animations/

repositories:
  - id: maven-central
    url: https://repo.maven.apache.org/maven2/
